#!/bin/sh

set -e

# the keyring in /var that gets fetched by apt-key net-update
# if it does not yet exist, copy it to avoid uneeded net copy
KEYRINGDIR="/etc/apt/trusted.gpg.d"
KEYRING="${KEYRINGDIR}/contactless-keyring.gpg"

if ! test -d $KEYRINGDIR; then
     mkdir -m 755 -p $KEYRINGDIR
fi

if ! test -f $KEYRING; then
     cp /usr/share/keyrings/contactless-keyring.gpg $KEYRING
     touch $KEYRING
fi

# make sure apt knows about the new keys
if [ -x /usr/bin/apt-key ]; then
    apt-key update
fi

#DEBHELPER#

exit 0
